// To parse this JSON data, do
//
//     final languageModel = languageModelFromJson(jsonString);

import 'package:meta/meta.dart';
import 'dart:convert';

LanguageModel languageModelFromJson(String str) => LanguageModel.fromJson(json.decode(str));

String languageModelToJson(LanguageModel data) => json.encode(data.toJson());

class LanguageModel {
  LanguageModel({
    required this.gzleg,
    required this.taryhyn,
    required this.teklipleri,
    required this.harytlar,
    required this.haryt,
    required this.filter,
    required this.aralykBaha,
    required this.min,
    required this.max,
    required this.taze,
    required this.halady,
    required this.bahasy,
    required this.tertiplemek,
    required this.onki,
    required this.bahaArzan,
    required this.bahaGymmat,
    required this.tazeHaryt,
    required this.satylanlar,
    required this.result,
    required this.arzanlan,
    required this.paylas,
    required this.arassa,
    required this.size,
    required this.detallar,
    required this.menzes,
    required this.haladym,
    required this.admin,
    required this.sebetAdd,
    required this.razmer,
    required this.aksiya,
    required this.mukdar,
    required this.asksiya,
    required this.tzeler,
    required this.arzan,
    required this.topPro,
    required this.top,
    required this.kategoriya,
    required this.dkan,
    required this.all,
    required this.order,
    required this.sebet,
    required this.zakaz,
    required this.sargyt,
    required this.info,
    required this.address,
    required this.ady,
    required this.telef,
    required this.note,
    required this.tanysdym,
    required this.borcnama,
    required this.eltip,
    required this.suGun,
    required this.ertir,
    required this.tleg,
    required this.nagtDal,
    required this.nagt,
    required this.online,
    required this.sarga,
    required this.home,
    required this.hyzmat,
    required this.cate,
    required this.profile,
    required this.profileDetails,
    required this.gosmaca,
  });

  String gzleg;
  String taryhyn;
  String teklipleri;
  String harytlar;
  String haryt;
  String filter;
  String aralykBaha;
  String min;
  String max;
  String taze;
  String halady;
  String bahasy;
  String tertiplemek;
  String onki;
  String bahaArzan;
  String bahaGymmat;
  String tazeHaryt;
  String satylanlar;
  String result;
  String arzanlan;
  String paylas;
  String arassa;
  String size;
  String detallar;
  String menzes;
  String haladym;
  String admin;
  String sebetAdd;
  String razmer;
  String aksiya;
  String mukdar;
  String asksiya;
  String tzeler;
  String arzan;
  String topPro;
  String top;
  String kategoriya;
  String dkan;
  String all;
  String order;
  String sebet;
  String zakaz;
  String sargyt;
  String info;
  String address;
  String ady;
  String telef;
  String note;
  String tanysdym;
  String borcnama;
  String eltip;
  String suGun;
  String ertir;
  String tleg;
  String nagtDal;
  String nagt;
  String online;
  String sarga;
  String home;
  String hyzmat;
  String cate;
  String profile;
  ProfileDetails profileDetails;
  Gosmaca gosmaca;

  factory LanguageModel.fromJson(Map<String, dynamic> json) => LanguageModel(
    gzleg: json["gözleg"],
    taryhyn: json["taryhyn"],
    teklipleri: json["teklipleri"],
    harytlar: json["harytlar"],
    haryt: json["haryt"],
    filter: json["filter"],
    aralykBaha: json["aralyk_baha"],
    min: json["min"],
    max: json["max"],
    taze: json["taze"],
    halady: json["halady"],
    bahasy: json["bahasy"],
    tertiplemek: json["tertiplemek"],
    onki: json["onki"],
    bahaArzan: json["baha_arzan"],
    bahaGymmat: json["baha_gymmat"],
    tazeHaryt: json["taze_haryt"],
    satylanlar: json["satylanlar"],
    result: json["result"],
    arzanlan: json["arzanlan"],
    paylas: json["paylas"],
    arassa: json["arassa"],
    size: json["size"],
    detallar: json["detallar"],
    menzes: json["menzes"],
    haladym: json["haladym"],
    admin: json["admin"],
    sebetAdd: json["sebet_add"],
    razmer: json["razmer"],
    aksiya: json["aksiya"],
    mukdar: json["mukdar"],
    asksiya: json["asksiya"],
    tzeler: json["täzeler"],
    arzan: json["arzan"],
    topPro: json["top_pro"],
    top: json["top"],
    kategoriya: json["kategoriya"],
    dkan: json["dükan"],
    all: json["all"],
    order: json["order"],
    sebet: json["sebet"],
    zakaz: json["zakaz"],
    sargyt: json["sargyt"],
    info: json["info"],
    address: json["address"],
    ady: json["ady"],
    telef: json["telef"],
    note: json["note"],
    tanysdym: json["tanysdym"],
    borcnama: json["borcnama"],
    eltip: json["eltip"],
    suGun: json["su_gun"],
    ertir: json["ertir"],
    tleg: json["töleg"],
    nagtDal: json["nagt_dal"],
    nagt: json["nagt"],
    online: json["online"],
    sarga: json["sarga"],
    home: json["home"],
    hyzmat: json["hyzmat"],
    cate: json["cate"],
    profile: json["profile"],
    profileDetails: ProfileDetails.fromJson(json["profile_details"]),
    gosmaca: Gosmaca.fromJson(json["gosmaca"]),
  );

  Map<String, dynamic> toJson() => {
    "gözleg": gzleg,
    "taryhyn": taryhyn,
    "teklipleri": teklipleri,
    "harytlar": harytlar,
    "haryt": haryt,
    "filter": filter,
    "aralyk_baha": aralykBaha,
    "min": min,
    "max": max,
    "taze": taze,
    "halady": halady,
    "bahasy": bahasy,
    "tertiplemek": tertiplemek,
    "onki": onki,
    "baha_arzan": bahaArzan,
    "baha_gymmat": bahaGymmat,
    "taze_haryt": tazeHaryt,
    "satylanlar": satylanlar,
    "result": result,
    "arzanlan": arzanlan,
    "paylas": paylas,
    "arassa": arassa,
    "size": size,
    "detallar": detallar,
    "menzes": menzes,
    "haladym": haladym,
    "admin": admin,
    "sebet_add": sebetAdd,
    "razmer": razmer,
    "aksiya": aksiya,
    "mukdar": mukdar,
    "asksiya": asksiya,
    "täzeler": tzeler,
    "arzan": arzan,
    "top_pro": topPro,
    "top": top,
    "kategoriya": kategoriya,
    "dükan": dkan,
    "all": all,
    "order": order,
    "sebet": sebet,
    "zakaz": zakaz,
    "sargyt": sargyt,
    "info": info,
    "address": address,
    "ady": ady,
    "telef": telef,
    "note": note,
    "tanysdym": tanysdym,
    "borcnama": borcnama,
    "eltip": eltip,
    "su_gun": suGun,
    "ertir": ertir,
    "töleg": tleg,
    "nagt_dal": nagtDal,
    "nagt": nagt,
    "online": online,
    "sarga": sarga,
    "home": home,
    "hyzmat": hyzmat,
    "cate": cate,
    "profile": profile,
    "profile_details": profileDetails.toJson(),
    "gosmaca": gosmaca.toJson(),
  };
}

class Gosmaca {
  Gosmaca({
    required this.totanleyin,
    required this.filer,
    required this.result,
    required this.bahaArasy,
    required this.sebedeGos,
    required this.haladym,
    required this.paylasMugt,
    required this.paylas,
    required this.sebet,
    required this.baskaAdd,
    required this.zakaz,
    required this.surady,
    required this.maglumat,
    required this.halanlardan,
    required this.dil,
    required this.addresAdd,
    required this.salgynyz,
    required this.salgyFull,
    required this.bizBarada,
    required this.biz,
    required this.serler,
    required this.habarlas,
    required this.sizin,
  });

  String totanleyin;
  String filer;
  String result;
  String bahaArasy;
  String sebedeGos;
  String haladym;
  String paylasMugt;
  String paylas;
  String sebet;
  String baskaAdd;
  String zakaz;
  String surady;
  String maglumat;
  String halanlardan;
  String dil;
  String addresAdd;
  String salgynyz;
  String salgyFull;
  String bizBarada;
  String biz;
  String serler;
  String habarlas;
  String sizin;

  factory Gosmaca.fromJson(Map<String, dynamic> json) => Gosmaca(
    totanleyin: json["totanleyin"],
    filer: json["filer"],
    result: json["result"],
    bahaArasy: json["baha_arasy"],
    sebedeGos: json["sebede_gos"],
    haladym: json["haladym"],
    paylasMugt: json["paylas_mugt"],
    paylas: json["paylas"],
    sebet: json["Sebet"],
    baskaAdd: json["baska_add"],
    zakaz: json["zakaz"],
    surady: json["surady"],
    maglumat: json["maglumat"],
    halanlardan: json["halanlardan"],
    dil: json["dil"],
    addresAdd: json["addres_add"],
    salgynyz: json["salgynyz"],
    salgyFull: json["salgy_full"],
    bizBarada: json["biz_barada"],
    biz: json["biz"],
    serler: json["serler"],
    habarlas: json["habarlas"],
    sizin: json["sizin"],
  );

  Map<String, dynamic> toJson() => {
    "totanleyin": totanleyin,
    "filer": filer,
    "result": result,
    "baha_arasy": bahaArasy,
    "sebede_gos": sebedeGos,
    "haladym": haladym,
    "paylas_mugt": paylasMugt,
    "paylas": paylas,
    "Sebet": sebet,
    "baska_add": baskaAdd,
    "zakaz": zakaz,
    "surady": surady,
    "maglumat": maglumat,
    "halanlardan": halanlardan,
    "dil": dil,
    "addres_add": addresAdd,
    "salgynyz": salgynyz,
    "salgy_full": salgyFull,
    "biz_barada": bizBarada,
    "biz": biz,
    "serler": serler,
    "habarlas": habarlas,
    "sizin": sizin,
  };
}

class ProfileDetails {
  ProfileDetails({
    required this.profile,
    required this.ady,
    required this.login,
    required this.phone,
    required this.yatda,
    required this.sargyt,
    required this.garas,
    required this.yatyryl,
    required this.taryhym,
    required this.ocur,
    required this.poz,
    required this.halanlarym,
    required this.admin,
    required this.saher,
    required this.setting,
    required this.dil,
    required this.salgy,
    required this.komek,
    required this.gorag,
    required this.sert,
    required this.barad,
    required this.habar,
    required this.paylas,
    required this.addressAdd,
    required this.salg,
    required this.salgyInfp,
    required this.uytget,
    required this.aar,
    required this.hzir,
    required this.aarSoz,
    required this.tasyk,
    required this.email,
    required this.haty,
    required this.ugrat,
    required this.editAddress,
    required this.saherWel,
    required this.full,
    required this.deleteAd,
    required this.yes,
    required this.no,
  });

  String profile;
  String ady;
  String login;
  String phone;
  String yatda;
  String sargyt;
  String garas;
  String yatyryl;
  String taryhym;
  String ocur;
  String poz;
  String halanlarym;
  String admin;
  String saher;
  String setting;
  String dil;
  String salgy;
  String komek;
  String gorag;
  String sert;
  String barad;
  String habar;
  String paylas;
  String addressAdd;
  String salg;
  String salgyInfp;
  String uytget;
  String aar;
  String hzir;
  String aarSoz;
  String tasyk;
  String email;
  String haty;
  String ugrat;
  String editAddress;
  String saherWel;
  String full;
  String deleteAd;
  String yes;
  String no;

  factory ProfileDetails.fromJson(Map<String, dynamic> json) => ProfileDetails(
    profile: json["profile"],
    ady: json["ady"],
    login: json["login"],
    phone: json["phone"],
    yatda: json["yatda"],
    sargyt: json["sargyt"],
    garas: json["garas"],
    yatyryl: json["yatyryl"],
    taryhym: json["taryhym"],
    ocur: json["ocur"],
    poz: json["poz"],
    halanlarym: json["halanlarym"],
    admin: json["admin"],
    saher: json["saher"],
    setting: json["setting"],
    dil: json["dil"],
    salgy: json["salgy"],
    komek: json["komek"],
    gorag: json["gorag"],
    sert: json["sert"],
    barad: json["barad"],
    habar: json["habar"],
    paylas: json["paylas"],
    addressAdd: json["address_add"],
    salg: json["salg"],
    salgyInfp: json["salgy_infp"],
    uytget: json["uytget"],
    aar: json["açar"],
    hzir: json["häzir"],
    aarSoz: json["açar_soz"],
    tasyk: json["tasyk"],
    email: json["email"],
    haty: json["haty"],
    ugrat: json["ugrat"],
    editAddress: json["edit_address"],
    saherWel: json["saher_wel"],
    full: json["full"],
    deleteAd: json["delete_ad"],
    yes: json["yes"],
    no: json["no"],
  );

  Map<String, dynamic> toJson() => {
    "profile": profile,
    "ady": ady,
    "login": login,
    "phone": phone,
    "yatda": yatda,
    "sargyt": sargyt,
    "garas": garas,
    "yatyryl": yatyryl,
    "taryhym": taryhym,
    "ocur": ocur,
    "poz": poz,
    "halanlarym": halanlarym,
    "admin": admin,
    "saher": saher,
    "setting": setting,
    "dil": dil,
    "salgy": salgy,
    "komek": komek,
    "gorag": gorag,
    "sert": sert,
    "barad": barad,
    "habar": habar,
    "paylas": paylas,
    "address_add": addressAdd,
    "salg": salg,
    "salgy_infp": salgyInfp,
    "uytget": uytget,
    "açar": aar,
    "häzir": hzir,
    "açar_soz": aarSoz,
    "tasyk": tasyk,
    "email": email,
    "haty": haty,
    "ugrat": ugrat,
    "edit_address": editAddress,
    "saher_wel": saherWel,
    "full": full,
    "delete_ad": deleteAd,
    "yes": yes,
    "no": no,
  };
}
